# Generated by Django 4.2.1 on 2023-05-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fifomodel",
            name="amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
