# Generated by Django 4.2.1 on 2023-05-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_fifomodel_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="avgbuyingpricecal",
            name="user",
            field=models.CharField(default="neha", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fifomodel",
            name="user",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
